version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "discontent-production"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1hrien2b75gym"
s3_prefix = "discontent-production"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
